import type { Metadata } from 'next'
import Head from 'next/head'
import './globals.scss'
import Header from "@/app/ui/Header";
import Footer from "@/app/ui/Footer";



export const metadata: Metadata = {
  title: 'lorem',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
        <script async type="text/javascript" src='./y-metrika/script.js' />
    </Head>

      <body  >
      <Header/>
      {children}
      <Footer/>
      </body>

    </html>
  )
}
