import { Space_Mono,Work_Sans } from 'next/font/google'
import type { Metadata } from 'next'
import Head from 'next/head'
import './globals.scss'
import Header from "@/app/ui/Header";
import Footer from "@/app/ui/Footer";

const spaseMomo = Space_Mono({
  style:['italic'],
  weight: ['400','700'],
  subsets:['latin'],
  display:'swap',
  variable:'--font-family'
})
const workSans =Work_Sans({
  weight:['100','200','300','400','500','600','700','800','900'],
  display:'swap',
  subsets:['latin'],
  style: ['italic'],
  variable:'--second-family'
})


export const metadata: Metadata = {
  title: 'lorem',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // onLoad="this.rel='stylesheet'"
  return (
    <html lang="en">
    <Head>
        <script async type="text/javascript" src='./y-metrika/script.js' />
      <link rel="preload" as="style" fetchPriority={'low'} media="all"
            href={' &family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap'}/>


    </Head>

      <body className={spaseMomo.variable+' '+workSans.variable} >
      <Header/>
      {children}
      <Footer/>
      </body>

    </html>
  )
}
